Loading cuda/11.3
  Loading requirement: cudnn/8.2.1-cu11.3
/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/torch/package/_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._utils' (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "/home/raecker1/nako_ukb_age/experiments/gradcam_volume_ukb.py", line 6, in <module>
    from pytorch_lightning import Trainer, seed_everything
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from lightning_lite.utilities.seed import seed_everything  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/__init__.py", line 23, in <module>
    from lightning_lite.lite import LightningLite  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/lite.py", line 29, in <module>
    from lightning_lite.plugins import Precision  # avoid circular imports: # isort: split
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/__init__.py", line 14, in <module>
    from lightning_lite.plugins.environments.cluster_environment import ClusterEnvironment
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/__init__.py", line 16, in <module>
    from lightning_lite.plugins.environments.lightning import LightningEnvironment  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/lightning.py", line 19, in <module>
    from lightning_lite.utilities.rank_zero import rank_zero_only
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/__init__.py", line 16, in <module>
    from lightning_lite.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/apply_func.py", line 19, in <module>
    import numpy as np
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/_globals.py", line 20, in <module>
    from ._utils import set_module as _set_module
ModuleNotFoundError: No module named 'numpy._utils'
/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/torch/package/_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._utils' (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "/home/raecker1/nako_ukb_age/experiments/gradcam_volume_ukb.py", line 6, in <module>
    from pytorch_lightning import Trainer, seed_everything
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from lightning_lite.utilities.seed import seed_everything  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/__init__.py", line 23, in <module>
    from lightning_lite.lite import LightningLite  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/lite.py", line 29, in <module>
    from lightning_lite.plugins import Precision  # avoid circular imports: # isort: split
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/__init__.py", line 14, in <module>
    from lightning_lite.plugins.environments.cluster_environment import ClusterEnvironment
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/__init__.py", line 16, in <module>
    from lightning_lite.plugins.environments.lightning import LightningEnvironment  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/lightning.py", line 19, in <module>
    from lightning_lite.utilities.rank_zero import rank_zero_only
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/__init__.py", line 16, in <module>
    from lightning_lite.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/apply_func.py", line 19, in <module>
    import numpy as np
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/_globals.py", line 20, in <module>
    from ._utils import set_module as _set_module
ModuleNotFoundError: No module named 'numpy._utils'
/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/torch/package/_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._utils' (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "/home/raecker1/nako_ukb_age/experiments/gradcam_volume_ukb.py", line 6, in <module>
    from pytorch_lightning import Trainer, seed_everything
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from lightning_lite.utilities.seed import seed_everything  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/__init__.py", line 23, in <module>
    from lightning_lite.lite import LightningLite  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/lite.py", line 29, in <module>
    from lightning_lite.plugins import Precision  # avoid circular imports: # isort: split
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/__init__.py", line 14, in <module>
    from lightning_lite.plugins.environments.cluster_environment import ClusterEnvironment
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/__init__.py", line 16, in <module>
    from lightning_lite.plugins.environments.lightning import LightningEnvironment  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/lightning.py", line 19, in <module>
    from lightning_lite.utilities.rank_zero import rank_zero_only
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/__init__.py", line 16, in <module>
    from lightning_lite.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/apply_func.py", line 19, in <module>
    import numpy as np
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/_globals.py", line 20, in <module>
    from ._utils import set_module as _set_module
ModuleNotFoundError: No module named 'numpy._utils'
/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/torch/package/_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._utils' (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "/home/raecker1/nako_ukb_age/experiments/gradcam_volume_ukb.py", line 6, in <module>
    from pytorch_lightning import Trainer, seed_everything
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from lightning_lite.utilities.seed import seed_everything  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/__init__.py", line 23, in <module>
    from lightning_lite.lite import LightningLite  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/lite.py", line 29, in <module>
    from lightning_lite.plugins import Precision  # avoid circular imports: # isort: split
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/__init__.py", line 14, in <module>
    from lightning_lite.plugins.environments.cluster_environment import ClusterEnvironment
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/__init__.py", line 16, in <module>
    from lightning_lite.plugins.environments.lightning import LightningEnvironment  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/lightning.py", line 19, in <module>
    from lightning_lite.utilities.rank_zero import rank_zero_only
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/__init__.py", line 16, in <module>
    from lightning_lite.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/apply_func.py", line 19, in <module>
    import numpy as np
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/_globals.py", line 20, in <module>
    from ._utils import set_module as _set_module
ModuleNotFoundError: No module named 'numpy._utils'
/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/torch/package/_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy._utils' (Triggered internally at  /opt/conda/conda-bld/pytorch_1640811803361/work/torch/csrc/utils/tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
Traceback (most recent call last):
  File "/home/raecker1/nako_ukb_age/experiments/gradcam_volume_ukb.py", line 6, in <module>
    from pytorch_lightning import Trainer, seed_everything
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from lightning_lite.utilities.seed import seed_everything  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/__init__.py", line 23, in <module>
    from lightning_lite.lite import LightningLite  # noqa: E402
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/lite.py", line 29, in <module>
    from lightning_lite.plugins import Precision  # avoid circular imports: # isort: split
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/__init__.py", line 14, in <module>
    from lightning_lite.plugins.environments.cluster_environment import ClusterEnvironment
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/__init__.py", line 16, in <module>
    from lightning_lite.plugins.environments.lightning import LightningEnvironment  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/plugins/environments/lightning.py", line 19, in <module>
    from lightning_lite.utilities.rank_zero import rank_zero_only
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/__init__.py", line 16, in <module>
    from lightning_lite.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/raecker1/envs/bio_age/lib/python3.9/site-packages/lightning_lite/utilities/apply_func.py", line 19, in <module>
    import numpy as np
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/__init__.py", line 105, in <module>
    from ._globals import _NoValue, _CopyMode
  File "/home/raecker1/.local/lib/python3.9/site-packages/numpy/_globals.py", line 20, in <module>
    from ._utils import set_module as _set_module
ModuleNotFoundError: No module named 'numpy._utils'
